name       : liblc3
version    : 1.0.3
release    : 1
source     :
    - https://github.com/google/liblc3/archive/refs/tags/v1.0.3.tar.gz : 33318036a4b83af697b328e55e8c5fab9763836083bccb586f4dc2e644c24991
license    : Apache-2.0
component  : multimedia.codecs
summary    : Low Complexity Communication Codec library and tools
description: |
    Low Complexity Communication Codec library and tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
